[versions]
quarkus = "3.24.3"

[libraries]
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
quarkus-extension = { id = "io.quarkus.extension", version.ref = "quarkus" }